name: Deploy Azure Resources with PowerShell

on:
  workflow_dispatch:

env:
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  LOCATION: 'westeurope'
  SHORT_LOCATION: 'weu'
  SUBSCRIPTION_ID: 'b2fe2be6-a721-41e9-a5c3-6b45a3765f76'

jobs:
  deploy:
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout repository   # Checkout your code
        uses: actions/checkout@v3
              
      - name: Install Azure PowerShell # 🛠️ Install Azure PowerShell
        run: |
          pwsh -Command "Install-Module -Name Az -Force -Scope CurrentUser -AllowClobber"
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy
        id: deploy_rg
        uses: azure/powershell@v1
        with:
          inlineScript: |
            # Authenticate to Azure
            Write-Host "Authenticating with Azure..."
            $creds = $env:AZURE_CREDENTIALS | ConvertFrom-Json
            $tenantId = $creds.tenantId 
            $appId =  $creds.clientId  # Also known as Client ID
            $sqlAdminpwd = $creds.sqlAdminPassword

            # "Start deploy to Azure"
            Write-Host " Deploy to Azure..."
            $resourceGroupName = 'AZ-Predict-${{ env.SHORT_LOCATION }}-rg'
            
            $secret = $creds.clientSecret
            $secureSecret = ConvertTo-SecureString $secret -AsPlainText -Force
            $credential = New-Object System.Management.Automation.PSCredential ($appId, $secureSecret)
            Connect-AzAccount -ServicePrincipal -Tenant $tenantId -Credential $credential

            Write-Host "Connected to Azure as Service Principal: $appId"
            Write-Host "Using subscription ID: $($creds.subscriptionId)"

            Write-Host "Setting subscription context..."
            Set-AzContext -SubscriptionId $creds.subscriptionId

            Write-Host "Creating resource group if it doesn't exist..."
            if (-not (Get-AzResourceGroup -Name $resourceGroupName -ErrorAction SilentlyContinue)) {
              New-AzResourceGroup -Name $resourceGroupName -Location ${{ env.LOCATION }}
            }
            echo "sqlAdminPwd=$sqlAdminPwd" >> $env:GITHUB_OUTPUT
            echo "resourceGroupName=$resourceGroupName" >> $env:GITHUB_OUTPUT
            Write-Host "-------------- Using sqlAdminpwd : $sqlAdminpwd"
          azPSVersion: "latest"
      - name: Deploy Bicep Template
        id: deploy_bicep
        uses: azure/arm-deploy@v1
        with:
            resourceGroupName: ${{ steps.deploy_rg.outputs.resourceGroupName }}
            template: ./infra/azure-deploy.bicep
            parameters: |
              deploymentLocation=${{ env.LOCATION }} sqlAdminPassword=${{ steps.deploy_rg.outputs.sqlAdminPwd }}
            deploymentMode: Incremental
